//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessDuck.Client.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localizations {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localizations() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FitnessDuck.Client.Localization.Localizations", typeof(Localizations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string day_week_short_monday {
            get {
                return ResourceManager.GetString("day_week_short_monday", resourceCulture);
            }
        }
        
        internal static string day_week_short_tuesday {
            get {
                return ResourceManager.GetString("day_week_short_tuesday", resourceCulture);
            }
        }
        
        internal static string day_week_short_wednesday {
            get {
                return ResourceManager.GetString("day_week_short_wednesday", resourceCulture);
            }
        }
        
        internal static string day_week_short_thursday {
            get {
                return ResourceManager.GetString("day_week_short_thursday", resourceCulture);
            }
        }
        
        internal static string day_week_short_friday {
            get {
                return ResourceManager.GetString("day_week_short_friday", resourceCulture);
            }
        }
        
        internal static string day_week_short_saturday {
            get {
                return ResourceManager.GetString("day_week_short_saturday", resourceCulture);
            }
        }
        
        internal static string day_week_short_sunday {
            get {
                return ResourceManager.GetString("day_week_short_sunday", resourceCulture);
            }
        }
        
        internal static string lesson_name_not_found {
            get {
                return ResourceManager.GetString("lesson_name_not_found", resourceCulture);
            }
        }
    }
}
